defaults:
  run:
    working-directory: desktop-app
on:
  push:
    paths:
      - 'desktop-app/**'
jobs:
  desktop-app:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] # if you want, enable linux with ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      #- run: sudo apt-get install libpango1.0-dev libatk1.0-dev libglib2.0-dev libgdk-pixbuf2.0-dev librust-gdk-sys-dev
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: desktop-app
          path: |
            desktop-app/target/release/tarkov-time.exe
            desktop-app/target/release/tarkov-time
